spring:
  application:
    name: jtexrer
  server:
    port: 8080
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
logging:
  level:
    .: warning
    mdse.jtexrer: debug
---
spring.profiles.group.production: online,h2infile,cron5pastmidnight,standardspread
spring.profiles.group.development: offline,h2infile,cronevery1min,standardspread
---
spring.config.activate.on-profile: postgresInDocker
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5454/jtexer?current_schema=public
    driverClassName: org.postgresql.Driver
    username: sa
    password: admin
---
spring.config.activate.on-profile: h2infile
spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/db/h2
    username: sa
    password: admin
  h2:
    console:
      enabled: true
---
spring.config.activate.on-profile: online
currency_exchange_api_url: https://api.apilayer.com/fixer/latest
currency_exchange_api_key_name: apikey
currency_exchange_api_key_value: cNjdRJ25uzrbKd88XRsOX1T6zYaTgAO1
---
spring.config.activate.on-profile: offline
currency_exchange_api_url: ""
currency_exchange_api_key_name: ""
currency_exchange_api_key_value: ""
---
spring.config.activate.on-profile: cronevery1min
fetch_schedule: 01 * * * * *
---
spring.config.activate.on-profile: cron5pastmidnight
fetch_schedule: 00 05 00 * * *
---