spring:
  profiles:
    active: h2
  application:
    name: jtexrer
  server:
    port: 8085
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  level:
    .: warning
    mdse.jtexrer: debug

---
spring:
  config:
    activate:
      on-profile: docker
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      datasource:
        url: jdbc:postgresql://localhost:5432/jtexer?current_schema=public
        driverClassName: org.postgresql.Driver
        username: sa
        password: admin
      liquibase:
        parameters:
          textColumnType: TEXT
        contexts: nonprod
---
spring:
  config:
    activate:
      on-profile: h2
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
      datasource:
        platform: h2
        url: jdbc:h2:file:./src/main/resources/db/h2
        driverClassName: org.h2.Driver
        username: sa
        password: admin
      liquibase:
        parameters:
          textColumnType: VARCHAR(250)
        contexts: nonprod
      h2:
        console:
          enabled: true
---
spring.config.activate.on-profile: offline
exchange_api_url: "dummy"
exchange_api_key_name: "dummy"
exchange_api_key_value: "dummy"
---
spring.config.activate.on-profile: every1min
schedule: 01 * * * * *
---
spring.config.activate.on-profile: 5pastmidnight
schedule: 00 05 00 * * *
---